.nh
.TH "gh" "1" "Mar 2021" "" ""

.SH NAME
.PP
gh\-repo\-list \- List repositories owned by user or organization


.SH SYNOPSIS
.PP
\fBgh repo list [] [flags]\fP


.SH DESCRIPTION
.PP
List repositories owned by user or organization


.SH OPTIONS
.PP
\fB\-\-archived\fP[=false]
	Show only archived repositories

.PP
\fB\-\-fork\fP[=false]
	Show only forks

.PP
\fB\-l\fP, \fB\-\-language\fP=""
	Filter by primary coding language

.PP
\fB\-L\fP, \fB\-\-limit\fP=30
	Maximum number of repositories to list

.PP
\fB\-\-no\-archived\fP[=false]
	Omit archived repositories

.PP
\fB\-\-private\fP[=false]
	Show only private repositories

.PP
\fB\-\-public\fP[=false]
	Show only public repositories

.PP
\fB\-\-source\fP[=false]
	Show only non\-forks


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-\-help\fP[=false]
	Show help for command


.SH SEE ALSO
.PP
\fBgh\-repo(1)\fP
